project_id = "cimixmdgcyozwmzboxfk"

[functions.generate-quote]
verify_jwt = false

[functions.send-quote]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.extract-keywords]
verify_jwt = false

[functions.recompute-user-profile]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.accept-team-invite]
verify_jwt = false