// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cimixmdgcyozwmzboxfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpbWl4bWRnY3lvendtemJveGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODM2OTEsImV4cCI6MjA4ODU1OTY5MX0.fEgTjp1kWP3Ffh0iwAppKK0JWsj40twlXHzRJTfwZBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});